language: python
python:
  - "3.5"

env:
  - DJANGO=1.8 MIGRATE='taskbuster/manage.py migrate'

before_install:
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
  - pip install -r requirements/testing.txt
  - pip install coveralls
  - pip install pyvirtualdisplay
  - sudo pip install tweepy

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - mysql -e 'CREATE DATABASE IF NOT EXISTS taskbuster_db;'

script:
  - git clone https://github.com/cms-dev/cms.git
  - cd cms
  - sudo python setup.py build
  - sudo python setup.py install
  - cd ..
  - sudo python setup.py develop
  - sudo python setup.py install
  - cd taskbuster/
  - python manage.py makemigrations
  - python manage.py migrate
  - django-admin compilemessages
  - coverage run --source='.' manage.py test -v 2

after_success:
  - coveralls

services:
  - mysql
