language: python
python:
  - "3.5"

env:
  - DJANGO=1.8 MIGRATE='taskbuster/manage.py migrate'

install:
  - pip install -r requirements/testing.txt
  - pip install coveralls

script:
  - python taskbuster/manage.py makemigrations
  - python taskbuster/manage.py migrate
  - coverage run taskbuster/manage.py test / -v 2

after_success:
  - coveralls
