# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_auto_20160616_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='percentage',
            field=models.CharField(default=50, help_text='Enter the percentage name', max_length=4, verbose_name='percentage'),
            preserve_default=False,
        ),
    ]
